### ISSUE TITLE
Notebook error on Ubuntu

### ISSUE THREAD

**Issue by alexarje** [balintlaczko/MGT-python#26]
When I try to open the notebook tutorial I get the following error: 

> Notebook validation failed: Additional properties are not allowed ('outputs', 'execution_count' were unexpected):
{
 "cell_type": "markdown",
 "execution_count": null,
 "metadata": {},
 "outputs": [],
 "source": "# Welcome to the Motion Gestures Toolbox (Python) - Tutorial/Documentation"
}

This is on Ubuntu 19.10

**Comment by balintlaczko** [comment]
Oi! Thank you, will look into that!

**Comment by balintlaczko** [comment]
I suspect this might be because I added some html tags earlier, will remove them in the next push!

**Comment by balintlaczko** [comment]
@alexarje try to pull it now and see if it works, I removed the html tags.

**Comment by alexarje** [comment]
See [here](https://github.com/bokeh/bokeh/issues/7057) that it was a version problem with conda. Doing: 

`conda install nbformat` 

solved the problem. Not sure if this is a general problem, or only on my system.

**Comment by alexarje** [comment]
Nope. The issue is still there on my Ubuntu machine (19.10): 

> An invalid notebook may not function properly. The validation error was:
> 
> Notebook validation failed: Additional properties are not allowed ('outputs', 'execution_count' were unexpected):
> {
>  "cell_type": "markdown",
>  "execution_count": null,
>  "metadata": {},
>  "outputs": [],
>  "source": "# Welcome to the Motion Gestures Toolbox (Python) - Tutorial/Documentation"
> }

**Comment by alexarje** [comment]
The notebook works, though.

**Comment by balintlaczko** [comment]
OK, that's strange. Basically it suggests that markdown cells are not allowed?.. I will set up a ubuntu in a vmware and test this.

**Comment by balintlaczko** [comment]
The notebook works for me on Ubuntu 19.10 (in virtualbox), loading it in VS Code. Which program do you use to open the notebook?

**Comment by alexarje** [comment]
I run jupyter notebook from the terminal and it opens in the browser. The notebook works, though, despite the error message.

**Comment by balintlaczko** [comment]
After some research it seems to be a problem either with VSCode + ipynb and/or version control (git) + ipynb. The problem is that each cell object gets an additional `outputs` and `execution_count` items. This does not prevent execution of the cells or normal functioning, but it is annoying. The solution is to remove these from each cell. There are several of such scripts orbiting related github threads, so I will just choose one which I can preferably hook to the save action in VSCode. If that is too complicated, I will just fix the notebook every time I commit some changes.

**Comment by alexarje** [comment]
Good. Let us just monitor this when we test on different platforms.

**Comment by balintlaczko** [comment]
This issue is a bit more mysterious than expected. I started to experiment with removing entries from cells, here is what I learned:

If I open the "original" notebook in the browser I get the same error as you did:

> Notebook validation failed: Additional properties are not allowed ('outputs', 'execution_count' were unexpected):
{
 "cell_type": "markdown",
 "execution_count": null,
 "metadata": {},
 "outputs": [],
 "source": "# Welcome to the Motion Gestures Toolbox (Python) - Tutorial/Documentation"
}

If I "manually" delete all `outputs` and `execution_count` elements, and try to open that notebook:

> Notebook validation failed: 'outputs' is a required property:
{
 "cell_type": "code",
 "metadata": {
  "trusted": false
 },
 "source": "import mgmodule"
}

If I bring back `outputs`:

> Notebook validation failed: Additional properties are not allowed ('outputs' was unexpected):
{
 "cell_type": "markdown",
 "metadata": {},
 "outputs": [],
 "source": "# Welcome to the Motion Gestures Toolbox (Python) - Tutorial/Documentation"
}

UPDATE: while writing this I realized that `outputs` should only get removed if "cell_type": "markdown". Will try that now.

**Comment by balintlaczko** [comment]
OK, so just to keep the info alive here: the real problem was that VSCode automatically adds the `outputs` and `execution_count` items to markdown cells too where they are not allowed. But in code cells they are required. So the solution was to remove them only from markdown cells.
